<?php

return [
    'host' => env('NEXPHANT_HOST', '0.0.0.0'),
    'port' => env('NEXPHANT_PORT', 8000),
    'quiet' => env('NEXPHANT_QUIET', true),
    'performance_mode' => env('NEXPHANT_PERFORMANCE_MODE', true),
    'runtime_safety' => env('NEXPHANT_RUNTIME_SAFETY', false),
    'event_loop' => env('NEXPHANT_LOOP', 'auto'),
    'socket_driver' => env('NEXPHANT_SOCKET', 'auto'),
    'max_connections' => env('NEXPHANT_MAX_CONNECTIONS', 4096),
    'backlog' => env('NEXPHANT_BACKLOG', 8192),
    'max_accept_per_tick' => env('NEXPHANT_MAX_ACCEPT_PER_TICK', 64),
    'keep_alive_timeout' => env('NEXPHANT_KEEP_ALIVE_TIMEOUT', 30),
    'max_requests' => env('NEXPHANT_MAX_REQUESTS', 10000),
    'max_request_size' => env('NEXPHANT_MAX_REQUEST_SIZE', 10 * 1024 * 1024),
    'max_write_buffer_size' => env('NEXPHANT_MAX_WRITE_BUFFER_SIZE', 1024 * 1024),
    'memory_limit' => env('NEXPHANT_MEMORY_LIMIT', 512 * 1024 * 1024),
    'memory_pressure_threshold' => env('NEXPHANT_MEMORY_PRESSURE_THRESHOLD', 0.90),
    'memory_hard_pressure_threshold' => env('NEXPHANT_MEMORY_HARD_PRESSURE_THRESHOLD', 0.97),
    'max_deferred' => env('NEXPHANT_MAX_DEFERRED', 100000),
    'max_read_callbacks_per_tick' => env('NEXPHANT_MAX_READ_CALLBACKS_PER_TICK', 1024),
    'max_write_callbacks_per_tick' => env('NEXPHANT_MAX_WRITE_CALLBACKS_PER_TICK', 1024),
    'max_deferred_per_tick' => env('NEXPHANT_MAX_DEFERRED_PER_TICK', 1024),
    'response_pool_size' => env('NEXPHANT_RESPONSE_POOL_SIZE', 4096),
    'request_pool_size' => env('NEXPHANT_REQUEST_POOL_SIZE', 4096),
    'buffer_pool_size' => env('NEXPHANT_BUFFER_POOL_SIZE', 8192),
    'metrics_sample_rate' => env('NEXPHANT_METRICS_SAMPLE_RATE', 100),
    'route_latency' => env('NEXPHANT_ROUTE_LATENCY', false),
    'histogram' => env('NEXPHANT_HISTOGRAM', false),
    'object_tracking' => env('NEXPHANT_OBJECT_TRACKING', false),
    'pool_safety' => env('NEXPHANT_POOL_SAFETY', false),
];
